# Netlify configuration for Aude Mouradian Architecture
# https://docs.netlify.com/configure-builds/file-based-configuration/

[build]
  publish = "dist"
  command = "npm run build:production"
  
[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"

# Build plugins
[[plugins]]
  package = "@netlify/plugin-lighthouse"
  
  [plugins.inputs]
    output_path = "reports/lighthouse"

# Redirects and rewrites
[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200
  
# API functions redirects
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Netlify CMS redirect  
[[redirects]]
  from = "/admin"
  to = "/admin/"
  status = 301

# SPA-like routing for client-side navigation
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  conditions = {Role = ["admin"]}

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "geolocation=(), microphone=(), camera=()"

# Admin section security
[[headers]]
  for = "/admin/*"
  [headers.values]
    X-Robots-Tag = "noindex, nofollow"

# API endpoints headers
[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type, Authorization"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"

# Cache static assets
[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/fonts/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Pagefind search files
[[headers]]
  for = "/pagefind/*"
  [headers.values]
    Cache-Control = "public, max-age=86400"

# Form processing (for Netlify Forms if needed as backup)
[forms]
  settings = true

# Environment variables (set these in Netlify UI)
# SUPABASE_URL
# SUPABASE_ANON_KEY
# SUPABASE_SERVICE_ROLE_KEY
# BREVO_API_KEY
# TURNSTILE_SECRET_KEY

# Dev server configuration
[dev]
  command = "npm run dev"
  port = 4321
  targetPort = 4321
  autoLaunch = false